# This is a basic workflow to help you get started with Actions

name: Checkmarx AST Github Action

# Controls when the workflow will run
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkmarx AST CLI Action
        uses: checkmarx/ast-github-action@main #Github Action version
        with:
          base_uri: https://eu.ast.checkmarx.net/
          cx_tenant: beta_nova8
          cx_client_id: sast_cli_peres
          cx_client_secret: 2yfRA3YTvNNIFuuvKcWvwA3pt6a5KAJ6
          additional_params: --sca-filter '!**/Dockerfile,!**/docker-compose.yml'
